In [1]:
import torch
import numpy as np

## 1. indexing and slicing

In [8]:
tensor = torch.rand(2, 3)
print(f"1st row: {tensor[0]}")
print(f"1st col: {tensor[:, 0]}")
print(f"last col: {tensor[:, -1]}")
tensor[:, 1] = 0
print(tensor, tensor.device)

1st row: tensor([0.8738, 0.8820, 0.6595])
1st col: tensor([0.8738, 0.8613])
last col: tensor([0.6595, 0.9696])
tensor([[0.8738, 0.0000, 0.6595],
        [0.8613, 0.0000, 0.9696]]) cpu


## 2. concatenation and repeating
 · torch.cat: 处理tenser sequence，在现有维度上堆叠tensor sequence，dim数量不扩，指定dim的值变大\
 · torch.stack: 处理tenser sequence，新增1维，在该维度上堆叠指定的tensor sequence\
 · tensor.repeat: 处理tenser，堆叠本tensor的各维度，维度可以扩张。类似numpy.tile\
 · torch.repeat_interleave, tensor.repeat_interleave: 处理tenser，重复每个维度上的元素，类似numpy.repeat

### 2.1 torch.cat将tensor sequence在自身的某维度上做堆叠
· 被堆叠的sequence中的tensors必须有相同的shape，或者是empty tensor\
· dim参数取值不能超过input的维度数\
· output的维度数和input tensor相同

In [9]:
x = torch.rand(1, 2)
t1 = torch.cat([x, x], dim=1) # 在dim 1上堆，shape的dim 0大小不变
t2 = torch.cat([x, x], dim=0) # 在dim 0上堆，shape的dim 1大小不变
print('x is: ', x)
print('shape of x: ', x.shape)
print(t1, t1.shape)
print(t2, t2.shape)
print(len(x.shape) == len(t1.shape) == len(t2.shape)) # output还是2维

x is:  tensor([[0.4630, 0.5083]])
shape of x:  torch.Size([1, 2])
tensor([[0.4630, 0.5083, 0.4630, 0.5083]]) torch.Size([1, 4])
tensor([[0.4630, 0.5083],
        [0.4630, 0.5083]]) torch.Size([2, 2])
True


In [10]:
x = torch.tensor([[[1, 2, 0], [5, 6, 7]],
                  [[8, 9, 0], [3, 4, 5]]])
y = torch.tensor([[[1, 1, 1], [2, 2, 2]],
                  [[0, 0, 0], [9, 9, 9]]])
t1 = torch.cat([x, y], dim=0) # 在dim 0上堆，shape的dim 1,2大小不变
t2 = torch.cat([x, y], dim=1) # 在dim 1上堆，shape的dim 0,2大小不变
t3 = torch.cat([x, y], dim=2) # 在dim 2上堆，shape的dim 1,2大小不变
print('原x:\n',x, x.shape)
print('原y:\n',y, y.shape)
print('在dim 0上堆:\n', t1, t1.shape)
print('在dim 1上堆:\n', t2, t2.shape)
print('在dim 2上堆:\n', t3, t3.shape)

原x:
 tensor([[[1, 2, 0],
         [5, 6, 7]],

        [[8, 9, 0],
         [3, 4, 5]]]) torch.Size([2, 2, 3])
原y:
 tensor([[[1, 1, 1],
         [2, 2, 2]],

        [[0, 0, 0],
         [9, 9, 9]]]) torch.Size([2, 2, 3])
在dim 0上堆:
 tensor([[[1, 2, 0],
         [5, 6, 7]],

        [[8, 9, 0],
         [3, 4, 5]],

        [[1, 1, 1],
         [2, 2, 2]],

        [[0, 0, 0],
         [9, 9, 9]]]) torch.Size([4, 2, 3])
在dim 1上堆:
 tensor([[[1, 2, 0],
         [5, 6, 7],
         [1, 1, 1],
         [2, 2, 2]],

        [[8, 9, 0],
         [3, 4, 5],
         [0, 0, 0],
         [9, 9, 9]]]) torch.Size([2, 4, 3])
在dim 2上堆:
 tensor([[[1, 2, 0, 1, 1, 1],
         [5, 6, 7, 2, 2, 2]],

        [[8, 9, 0, 0, 0, 0],
         [3, 4, 5, 9, 9, 9]]]) torch.Size([2, 2, 6])


### 2.2 torch.stack将tensor sequence堆叠到新的维度
· 被堆叠的sequence中的tensors必须有相同的shape\
· output维度+1

In [11]:
y = torch.zeros(2, 3) 
z = torch.arange(1, 7).reshape(2, 3)
print('y is:', y)
print('z is:', z)
t3 = torch.stack([y, z], dim=0)
t4 = torch.stack([y, z], dim=1)
t5 = torch.stack([y, z], dim=2)  # dim取[-3, 2]
print(t3, t3.shape)
print(t4, t4.shape)
print(t5, t5.shape)
print(f"# dim of t3,t4,t5: {len(t3.shape), len(t4.shape), len(t5.shape)}")

y is: tensor([[0., 0., 0.],
        [0., 0., 0.]])
z is: tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 2., 3.],
         [4., 5., 6.]]]) torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [1., 2., 3.]],

        [[0., 0., 0.],
         [4., 5., 6.]]]) torch.Size([2, 2, 3])
tensor([[[0., 1.],
         [0., 2.],
         [0., 3.]],

        [[0., 4.],
         [0., 5.],
         [0., 6.]]]) torch.Size([2, 3, 2])
# dim of t3,t4,t5: (3, 3, 3)


In [12]:
x = torch.tensor([[[1, 2, 0], [5, 6, 7]],
                  [[8, 9, 0], [3, 4, 5]]])
y = torch.tensor([[[1, 1, 1], [2, 2, 2]],
                  [[0, 0, 0], [9, 9, 9]]])
t1 = torch.stack([x, y], dim=0) # 在dim 0上堆，shape的dim 1,2大小不变
t2 = torch.stack([x, y], dim=1) # 在dim 1上堆，shape的dim 0,2大小不变
t3 = torch.stack([x, y], dim=2) # 在dim 2上堆，shape的dim 1,2大小不变
print('原x:\n',x, x.shape)
print('原y:\n',y, y.shape)
print('在dim 0上堆:\n', t1, t1.shape)
print('在dim 1上堆:\n', t2, t2.shape)
print('在dim 2上堆:\n', t3, t3.shape)

原x:
 tensor([[[1, 2, 0],
         [5, 6, 7]],

        [[8, 9, 0],
         [3, 4, 5]]]) torch.Size([2, 2, 3])
原y:
 tensor([[[1, 1, 1],
         [2, 2, 2]],

        [[0, 0, 0],
         [9, 9, 9]]]) torch.Size([2, 2, 3])
在dim 0上堆:
 tensor([[[[1, 2, 0],
          [5, 6, 7]],

         [[8, 9, 0],
          [3, 4, 5]]],


        [[[1, 1, 1],
          [2, 2, 2]],

         [[0, 0, 0],
          [9, 9, 9]]]]) torch.Size([2, 2, 2, 3])
在dim 1上堆:
 tensor([[[[1, 2, 0],
          [5, 6, 7]],

         [[1, 1, 1],
          [2, 2, 2]]],


        [[[8, 9, 0],
          [3, 4, 5]],

         [[0, 0, 0],
          [9, 9, 9]]]]) torch.Size([2, 2, 2, 3])
在dim 2上堆:
 tensor([[[[1, 2, 0],
          [1, 1, 1]],

         [[5, 6, 7],
          [2, 2, 2]]],


        [[[8, 9, 0],
          [0, 0, 0]],

         [[3, 4, 5],
          [9, 9, 9]]]]) torch.Size([2, 2, 2, 3])


### 2.3 tensor.repeat(): 重复堆叠tensor.类似numpy.tile
· 参数数量(number)决定在多少个维度上做堆叠，参数个数可以大于tensor维数\
· 每个参数值(value)指定对应维度的堆叠次数\
· 如tensor有d维，后d个参数指定d维上堆叠的次数，其他参数决定前序扩张维度上的堆叠次数

In [13]:
x = torch.tensor([1, 2, 3])  # dim=d, shape=(n,)
y0 = x.repeat(3)
y1 = x.repeat(3, 2)          # dim=2, shape=(3, 2*n)
y2 = x.repeat(2, 1, 2)       # dim=3, shape=(2, 1, 2*n)
y3 = x.repeat(2, 2, 1, 2)    # dim=4, shape=(2, 2, 1, 2*n)
print(y0, y0.shape)
print(y1, y1.shape)
print(y2, y2.shape)
print(y3, y3.shape)

tensor([1, 2, 3, 1, 2, 3, 1, 2, 3]) torch.Size([9])
tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]]) torch.Size([3, 6])
tensor([[[1, 2, 3, 1, 2, 3]],

        [[1, 2, 3, 1, 2, 3]]]) torch.Size([2, 1, 6])
tensor([[[[1, 2, 3, 1, 2, 3]],

         [[1, 2, 3, 1, 2, 3]]],


        [[[1, 2, 3, 1, 2, 3]],

         [[1, 2, 3, 1, 2, 3]]]]) torch.Size([2, 2, 1, 6])


In [14]:
x = torch.tensor([[1, 2, 0], [5, 6, 7]])  # dim=d=2, shape=(m, n)=(2, 3)
y1 = x.repeat(3, 2)                       # dim=2, shape=(3*m, 2*n)
y2 = x.repeat(2, 2, 3)                    # dim=3, shape=(2, 2*m, 3*n)
y3 = x.repeat(2, 2, 1, 1)                 # dim=4, shape=(2, 2, 1*m, 1*n)
print(y1, y1.shape)
print(y2, y2.shape)
print(y3, y3.shape)

tensor([[1, 2, 0, 1, 2, 0],
        [5, 6, 7, 5, 6, 7],
        [1, 2, 0, 1, 2, 0],
        [5, 6, 7, 5, 6, 7],
        [1, 2, 0, 1, 2, 0],
        [5, 6, 7, 5, 6, 7]]) torch.Size([6, 6])
tensor([[[1, 2, 0, 1, 2, 0, 1, 2, 0],
         [5, 6, 7, 5, 6, 7, 5, 6, 7],
         [1, 2, 0, 1, 2, 0, 1, 2, 0],
         [5, 6, 7, 5, 6, 7, 5, 6, 7]],

        [[1, 2, 0, 1, 2, 0, 1, 2, 0],
         [5, 6, 7, 5, 6, 7, 5, 6, 7],
         [1, 2, 0, 1, 2, 0, 1, 2, 0],
         [5, 6, 7, 5, 6, 7, 5, 6, 7]]]) torch.Size([2, 4, 9])
tensor([[[[1, 2, 0],
          [5, 6, 7]],

         [[1, 2, 0],
          [5, 6, 7]]],


        [[[1, 2, 0],
          [5, 6, 7]],

         [[1, 2, 0],
          [5, 6, 7]]]]) torch.Size([2, 2, 2, 3])


### 2.4 tensor.repeat_interleave(\<tensor>, \<n>, dim=?)
· 不指定参数dim=？时，输出会被flattened成1维\
· 参数dim决定元素在哪个维度上重复，n决定重复次数
· 第2个参数指定repeat的次数，如果是int，就是每个元素重复次数；如果是tensor，那么tensor的长度必须等于input tensor的长度，每个tensor的值决定input tensor中每个元素重复多少次

In [15]:
x = torch.tensor([[1, 2], [3, 4], [5, 6]])

y1 = x.repeat_interleave(2)
y2 = torch.repeat_interleave(x, 2)
print('flattened, 重复2次:',y1,'\n', y2)

y3 = torch.repeat_interleave(x, 2, dim=0)
print('沿dim0，重复2次:','\n', y3)
y4 = torch.repeat_interleave(x, 3, dim=1)
print('沿dim1，重复3次:','\n', y4)
y5 = torch.repeat_interleave(x, torch.tensor([1, 2, 1]), dim=0)
print('沿dim0，分别重复1， 2， 1次:','\n', y5)

flattened, 重复2次: tensor([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6]) 
 tensor([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])
沿dim0，重复2次: 
 tensor([[1, 2],
        [1, 2],
        [3, 4],
        [3, 4],
        [5, 6],
        [5, 6]])
沿dim1，重复3次: 
 tensor([[1, 1, 1, 2, 2, 2],
        [3, 3, 3, 4, 4, 4],
        [5, 5, 5, 6, 6, 6]])
沿dim0，分别重复1， 2， 1次: 
 tensor([[1, 2],
        [3, 4],
        [3, 4],
        [5, 6]])
