In [1]:
import torch

# Manipulating tensor shapes

### 3.2 tensor.reshape()
1. 通常情况下，reshape返回的tensor只是原tensor的一个view，两者指向的是相同的memory location。但实际使用的时候，不要依赖这里的view vs. copy关系，不然容易出错。
2. reshape实际上是打包了两种处理方式的method，当reshape的input tensor和outpu tensor的shape是compatible的时候，它调用的是tensor.view()，此时不copy data，当两者的shape不兼容的时候，它调用tensor.contiguous()，这时候就会copy data。
   - <font color=blue>· 可以理解成，处理contiguous tensor时，调用view();处理non-contiguous tensor时，调用contiguous(). </font>
3. pyrotch要求'shape'参数必须是tuple of ints。但是当shape是第一个参数的时候，可以用series if integers或者单个integer作为shape的值，但如果shape不是第一个参数，就必须是tuple。

· 注：在extent of dim为1时，要注意，x=(3)是int，x=(3,)是tuple

In [16]:
## tensor.reshape()的shape参数：x=(3)是int，不能用，x=(3,)是tuple
x = (1, 2, 3)
y = (3)
z = (2,)
print(type(x), type(y), type(z))

## 用tensor.reshape,这时shape参数是第一个参数
output3d = torch.ones(2, 2, 3)

input1d = output3d.reshape(12) # 12 = 2 * 2 * 3
print(input1d, input1d.shape)

## 用torch module的reshape method，这时shape参数不是第一个参数
# input1d_2 = torch.reshape(output3d, (12)) # 错,(12)被识别为int12
input1d_2 = torch.reshape(output3d, (12,))  # 用(12,)才是tuple
print(input1d_2.shape)

<class 'tuple'> <class 'int'> <class 'tuple'>
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]) torch.Size([12])
torch.Size([12])


In [17]:
## 处理contiguous tensor
x = torch.arange(1,13)
print(x, x.is_contiguous())

y = x.reshape(4,3)
print(y)
print(x.storage().data_ptr() == y.storage().data_ptr())

# 改变x中元素值, y也变
x[2] = 100
print(x, '\n')
print(y, '\n')

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]) True
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
True
tensor([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12]) 

tensor([[  1,   2, 100],
        [  4,   5,   6],
        [  7,   8,   9],
        [ 10,  11,  12]]) 



In [18]:
## 处理non-contiguous tensor
x = torch.arange(1,13).view(6,2).transpose(0,1)
print(x, x.is_contiguous())

y = x.reshape(4,3)
print(y)
print(x.storage().data_ptr() == y.storage().data_ptr())

# 改变x中元素值, y不变
x[1] = 100
print(x, '\n')
print(y, '\n')

tensor([[ 1,  3,  5,  7,  9, 11],
        [ 2,  4,  6,  8, 10, 12]]) False
tensor([[ 1,  3,  5],
        [ 7,  9, 11],
        [ 2,  4,  6],
        [ 8, 10, 12]])
False
tensor([[  1,   3,   5,   7,   9,  11],
        [100, 100, 100, 100, 100, 100]]) 

tensor([[ 1,  3,  5],
        [ 7,  9, 11],
        [ 2,  4,  6],
        [ 8, 10, 12]]) 

