In [33]:
import torch
import math
import torch.nn as nn
import torchviz
# 配置
device = torch.device('cuda')
dtype = torch.float

In [40]:
a = torch.ones(5, requires_grad = True)
b = 2*a

b.retain_grad()   # Since b is non-leaf and it's grad will be destroyed otherwise.

c = b.mean()

c.backward()

print(b.grad)

tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000])


In [44]:
a = torch.ones(5, requires_grad = True)
b = 2*a

b.register_hook(lambda x: print(x))  

b.mean().backward() 
print(a.grad)

tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000])
tensor([0.4000, 0.4000, 0.4000, 0.4000, 0.4000])


In [43]:
a = torch.ones(5, requires_grad = True)
b = 2*a
b.retain_grad()
b.mean().backward() 
b.grad *= 2
a.grad, b.grad # a的grad应该也改变，但是没有。所以还要手动改a的grad

(tensor([0.4000, 0.4000, 0.4000, 0.4000, 0.4000]),
 tensor([0.4000, 0.4000, 0.4000, 0.4000, 0.4000]))

In [ ]:
class rktestModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.aff1 = nn.Linear(20, 100)
        self.aff2 = nn.Linear(100, 10)
    
    def forward(self, x):
        x = self.aff1(x)
        x = F.relu(x)
        y = self.aff2(x)
        return y

net = rktestModule()
torch.manual_seed(2)
x = torch.randn(2, 20)
y = torch.randn(2, 10)

score = net(x)
loss = F.cross_entropy(score, y)
loss.backward()